# Generated by Django 4.0.4 on 2022-04-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('U', 'Upstairs Media Room'), ('D', 'Downstairs Living Room'), ('B', 'Borrowed')], default='U', max_length=1)),
                ('series', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
