# Generated by Django 4.0.4 on 2022-04-27 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='rental date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 4, 27, 3, 0, 11, 352058, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='returned',
            field=models.CharField(choices=[('O', 'Outstanding'), ('L', 'Late'), ('R', 'Returned'), ('D', 'Damaged'), ('V', 'Resolved')], default='O', max_length=1),
        ),
    ]
