# Generated by Django 4.0.4 on 2022-04-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_snack_delete_person_movie_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='snack',
            new_name='snacks',
        ),
      
    ]
